# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 薛彬的博客
brief-intro: Xue bin's Personal Growth Website
baseurl: "/blog" #the subpath of your site, e.g. /blog
#url: "http://axuebin.com/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  axuebin
email: xb@axuebin.com
weibo_username: 201251025

description_footer: 本站记录我这个小小程序猿的成长历程...

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: xb9207

google_analytics_id: UA-73786601-2 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 8
